### PR TITLE
Added Toggle  Button

### PR DESCRIPTION
**Pull request by AbdulRehmanGHub**
added this functionalies in your project

### CODE REVIEW

**Comment by AbdulRehmanGHub** [comment]
plz revivew it

**Review by UzairZQ — COMMENTED** [review]
Hey Abdul,

So you have created a new opensource.txt file right?

**Comment by AbdulRehmanGHub** [comment]
I was just trying to teach my friend "Sardar Idrees" about Open Source here at KPITB. I think he knows you.
Sorry for interruption.

**Comment by UzairZQ** [comment]
> I was just trying to teach my friend "Sardar Idrees" about Open Source here at KPITB. I think he knows you.
> Sorry for interruption.

Oh no worries, let me merge your contribution and say Salam to him from my side

**Review by UzairZQ — APPROVED** [review]

**Pull request closed without merging**
